---
title: "MGSC 661-075 - Lab 2"
output: html_notebook
author: "Lakshya Agarwal, Jatin Suri"
---

# Lab 2

```{r}
require(visreg)
require(glue)
require(car)
require(lmtest)
require(psych)
require(plm)
```

## Importing data

```{r}
data <- read.csv("./board_games_fall_2023.csv")
attach(data)
head(data)
```

## 1. Model Issues: Non-linearity

### `avg_rating = bo+ b1(year)+ b2(avg_timeplay)+b3(weight)`

#### Part A:

```{r}
library(car)
reg1 <- lm(avg_rating ~ year + avg_timeplay + weight)
residualPlots(reg1)
```

## 2. Model Issues: Heteroskedasticity

### `avg_rating = bo+ b1(avg_timeplay)`

#### Part B:

```{r}
library(car)
reg2 <- lm(avg_rating ~ avg_timeplay)
summary(reg2)
```

#### Part C:

```{r}
residualPlot(reg2, quadratic = FALSE)
```

#### Part D:

```{r}
ncvTest(reg2)
```

#### Part E:

```{r}
coeftest(reg2, vcov = vcovHC(reg2, type = "HC1"))
summary(reg2)
```

## 3. Model Issues: Outliers

### `avg_rating = bo+ b1(min_players)+ b2(age)+b2(num_votes)`

#### Part A:

```{r}
reg3 <- lm(avg_rating ~ min_players + age + num_votes)
summary(reg3)
outlierTest(reg3)
```

#### Part B:

```{r}
data[3124, ]
```

#### Part C:

```{r}
new_data <- data[-c(3124), ]
attach(new_data)
reg4 <- lm(avg_rating ~ min_players + age + num_votes)
summary(reg4)
```

## 4. Model Issues: Collinearity

### `avg_rating = bo+ b1(year)+b2(age)+b3(min_timeplay)+b4(max_timeplay)`

#### Part B:

```{r}
quantvars <- data[, c(7,8,9,12)]
corr_matrix <- cor(quantvars)
round(corr_matrix, 2)
```

#### Part D:

```{r}
reg5 <- lm(avg_rating~year+age+min_timeplay+max_timeplay)
vif(reg5)
```
